title: AGA Social
email: info@aga.social
description: >- # 
  AGA Social is an innovative company dedicated to developing artificial intelligence-powered software.
  We specialize in creating advanced technological solutions that transform the way businesses operate
  and connect with their customers.
  Our focus on artificial intelligence allows us to offer products and services that not only optimize
  processes but also drive efficiency and innovation across various industries.
default_image: /assets/images/default-social-image.jpg
baseurl: ""
url: "https://aga.social"
twitter_username: 
github_username: agasocial

# Language settings
lang: en
alternate_languages:
  - code: es
    url: /es/

# Theme and brand settings
theme_color: "#0066cc"
brand_color: "#0066cc"

# External domains for prefetch
external_domains:
  - https://fonts.googleapis.com
  - https://ajax.googleapis.com
  - https://cdn.jsdelivr.net

# SEO verification tokens (add your tokens when available)
#google_site_verification: ""
#bing_site_verification: ""
#pinterest_site_verification: ""

# Organization info for Schema.org
organization:
  name: AGA Social
  legal_name: AGA Social LLC
  url: https://aga.social
  logo: /assets/images/logo-w.png
  founding_date: 2022
  founders:
    - name: Alexander Ramírez
      title: Computer Engineer
    - name: Gabriel Vega
      title: Computer Engineer

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/